default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rswag-playground_development

test:
  <<: *default
  database: rswag-playground_test

production:
  <<: *default
  database: rswag-playground_production
  username: rswag-playground
  password: <%= ENV['ONE11_DATABASE_PASSWORD'] %>
